"""AST transformer: rewrite generated JAX Python source to MLX.

Transforms the Python code generated by openvaf_jax codegen so it uses
mlx.core instead of jax.numpy / jax.lax.  The generated code uses a small,
predictable set of JAX APIs (see CLAUDE.md "OpenVAF CallbackKind Handling"),
so we can do this mechanically at the AST level.

Usage
-----
    from scripts.jax_to_mlx import jax_to_mlx

    mlx_code = jax_to_mlx(jax_code)      # returns transformed source string
    exec(mlx_code, {"mx": mlx.core})     # run with MLX
"""

from __future__ import annotations

import ast
import sys
from typing import List, Optional

# ---------------------------------------------------------------------------
# Direct jnp.X -> mx.X mappings (no signature change)
# ---------------------------------------------------------------------------
_DIRECT_MAP = {
    "where", "exp", "log", "log10", "log2", "sqrt", "floor", "ceil",
    "sin", "cos", "tan", "sinh", "cosh", "tanh",
    "arcsin", "arccos", "arctan",
    "arcsinh", "arccosh", "arctanh",
    "abs", "power", "maximum", "minimum", "arctan2",
    "logical_not", "array",
}


class JaxToMlxTransformer(ast.NodeTransformer):
    """Rewrite a JAX-flavoured AST to an MLX-flavoured AST.

    Handles every API found across resistor, diode and PSP103 generated code:

    Direct renames (jnp.X -> mx.X):
        where, exp, log, sqrt, floor, power, maximum, array, logical_not, ...

    Special rewrites:
        jnp.inf        -> float('inf')
        jnp.nan        -> float('nan')
        jnp.bool_(x)   -> (x != 0)   [MLX bools from comparison]
        jnp.float64(x) -> mx.array(x, dtype=mx.float32)  [no f64 on Metal]
        jnp.float32(x) -> mx.array(x, dtype=mx.float32)
        jnp.int32(x)   -> mx.array(x, dtype=mx.int32)
        jnp.select(c, v, d) -> _mlx_select(c, v, d)  [helper injected]

    Structural rewrites:
        jax.tree_util.tree_map(fn, a, b)
            -> tuple(fn(*args) for args in zip(a, b))

        lax.while_loop(cond, body, init)
            -> _mlx_while_loop(cond, body, init)  [helper injected]

    Import rewrites:
        import jax                       -> import mlx.core as mx
        from jax import numpy as jnp, lax -> (removed, mx used directly)
    """

    def visit_Import(self, node: ast.Import) -> Optional[ast.stmt]:
        """import jax -> import mlx.core as mx"""
        for alias in node.names:
            if alias.name == "jax":
                return ast.parse("import mlx.core as mx").body[0]
        return node

    def visit_ImportFrom(self, node: ast.ImportFrom) -> Optional[ast.stmt]:
        """from jax import numpy as jnp, lax -> (drop, mx already imported)"""
        if node.module == "jax":
            return None  # remove the import
        return node

    # ----- Attribute access: jnp.X, lax.X ---------------------------------

    def visit_Attribute(self, node: ast.Attribute) -> ast.expr:
        self.generic_visit(node)

        # jnp.inf -> float('inf')
        if _is_name(node.value, "jnp") and node.attr == "inf":
            return _call("float", [ast.Constant(value="inf")])

        # jnp.nan -> float('nan')
        if _is_name(node.value, "jnp") and node.attr == "nan":
            return _call("float", [ast.Constant(value="nan")])

        # jnp.X (direct map) -> mx.X
        if _is_name(node.value, "jnp") and node.attr in _DIRECT_MAP:
            return ast.Attribute(
                value=ast.Name(id="mx", ctx=ast.Load()),
                attr=node.attr,
                ctx=node.ctx,
            )

        # jnp.X (anything else we haven't special-cased) -> mx.X
        # This catches future additions without needing to update _DIRECT_MAP
        if _is_name(node.value, "jnp"):
            return ast.Attribute(
                value=ast.Name(id="mx", ctx=ast.Load()),
                attr=node.attr,
                ctx=node.ctx,
            )

        return node

    # ----- Function calls: jnp.bool_(), jnp.float64(), tree_map, etc ------

    def visit_Call(self, node: ast.Call) -> ast.expr:
        # Check special cases BEFORE generic_visit transforms jnp -> mx
        func = node.func

        # --- jnp.bool_(x) -> (x != 0) for Python booleans ----------------
        if _is_jnp_attr(func, "bool_") and len(node.args) == 1:
            self.generic_visit(node)  # transform args
            arg = node.args[0]
            # If arg is already a boolean constant, keep it as-is
            if isinstance(arg, ast.Constant) and isinstance(arg.value, bool):
                return arg
            return ast.Compare(
                left=arg,
                ops=[ast.NotEq()],
                comparators=[ast.Constant(value=0)],
            )

        # --- jnp.float64(x) -> mx.array(x, dtype=mx.float32) -------------
        if _is_jnp_attr(func, "float64") and len(node.args) == 1:
            self.generic_visit(node)
            return _mx_array_cast(node.args[0], "float32")

        # --- jnp.float32(x) -> mx.array(x, dtype=mx.float32) -------------
        if _is_jnp_attr(func, "float32") and len(node.args) == 1:
            self.generic_visit(node)
            return _mx_array_cast(node.args[0], "float32")

        # --- jnp.int32(x) -> mx.array(x, dtype=mx.int32) -----------------
        if _is_jnp_attr(func, "int32") and len(node.args) == 1:
            self.generic_visit(node)
            return _mx_array_cast(node.args[0], "int32")

        # --- jnp.select(condlist, choicelist, default) --------------------
        #     -> _mlx_select(condlist, choicelist, default)
        if _is_jnp_attr(func, "select"):
            self.generic_visit(node)
            return ast.Call(
                func=ast.Name(id="_mlx_select", ctx=ast.Load()),
                args=node.args,
                keywords=node.keywords,
            )

        # --- jax.tree_util.tree_map(fn, *args) ----------------------------
        #     -> tuple(fn(*args) for args in zip(tree1, tree2, ...))
        if _is_tree_map(func) and len(node.args) >= 2:
            self.generic_visit(node)  # transform jnp.where inside lambda
            fn_arg = node.args[0]
            tree_args = node.args[1:]
            return _inline_tree_map(fn_arg, tree_args)

        # --- lax.while_loop(cond, body, init) -----------------------------
        #     -> _mlx_while_loop(cond, body, init)
        if _is_lax_attr(func, "while_loop"):
            self.generic_visit(node)
            return ast.Call(
                func=ast.Name(id="_mlx_while_loop", ctx=ast.Load()),
                args=node.args,
                keywords=node.keywords,
            )

        # Default: transform children normally
        self.generic_visit(node)

        return node


# ---------------------------------------------------------------------------
# Helper predicates
# ---------------------------------------------------------------------------

def _is_name(node: ast.expr, name: str) -> bool:
    return isinstance(node, ast.Name) and node.id == name


def _is_jnp_attr(node: ast.expr, attr: str) -> bool:
    return (
        isinstance(node, ast.Attribute)
        and node.attr == attr
        and _is_name(node.value, "jnp")
    )


def _is_lax_attr(node: ast.expr, attr: str) -> bool:
    return (
        isinstance(node, ast.Attribute)
        and node.attr == attr
        and _is_name(node.value, "lax")
    )


def _is_tree_map(node: ast.expr) -> bool:
    """Check for jax.tree_util.tree_map."""
    return (
        isinstance(node, ast.Attribute)
        and node.attr == "tree_map"
        and isinstance(node.value, ast.Attribute)
        and node.value.attr == "tree_util"
        and _is_name(node.value.value, "jax")
    )


# ---------------------------------------------------------------------------
# AST construction helpers
# ---------------------------------------------------------------------------

def _call(name: str, args: List[ast.expr]) -> ast.Call:
    return ast.Call(
        func=ast.Name(id=name, ctx=ast.Load()),
        args=args,
        keywords=[],
    )


def _mx_array_cast(value: ast.expr, dtype: str) -> ast.Call:
    """mx.array(value, dtype=mx.<dtype>)"""
    return ast.Call(
        func=ast.Attribute(
            value=ast.Name(id="mx", ctx=ast.Load()),
            attr="array",
            ctx=ast.Load(),
        ),
        args=[value],
        keywords=[
            ast.keyword(
                arg="dtype",
                value=ast.Attribute(
                    value=ast.Name(id="mx", ctx=ast.Load()),
                    attr=dtype,
                    ctx=ast.Load(),
                ),
            )
        ],
    )


def _inline_tree_map(fn: ast.expr, trees: List[ast.expr]) -> ast.Call:
    """tuple(fn(*args) for args in zip(tree1, tree2, ...))

    Replaces jax.tree_util.tree_map(fn, tree1, tree2) with a Python
    tuple comprehension — no JAX dependency needed.
    """
    # Build: zip(tree1, tree2, ...)
    zip_call = ast.Call(
        func=ast.Name(id="zip", ctx=ast.Load()),
        args=trees,
        keywords=[],
    )

    # Build: fn(*args)
    args_name = ast.Name(id="_tm_args", ctx=ast.Load())
    fn_call = ast.Call(
        func=fn,
        args=[ast.Starred(value=args_name, ctx=ast.Load())],
        keywords=[],
    )

    # Build: tuple(fn(*args) for args in zip(...))
    generator = ast.GeneratorExp(
        elt=fn_call,
        generators=[
            ast.comprehension(
                target=ast.Name(id="_tm_args", ctx=ast.Store()),
                iter=zip_call,
                ifs=[],
                is_async=0,
            )
        ],
    )

    return ast.Call(
        func=ast.Name(id="tuple", ctx=ast.Load()),
        args=[generator],
        keywords=[],
    )


# ---------------------------------------------------------------------------
# Public API
# ---------------------------------------------------------------------------

def jax_to_mlx(jax_source: str) -> str:
    """Transform JAX-generated Python source to MLX-compatible source.

    Args:
        jax_source: Python source code using jnp.*, jax.*, lax.* APIs

    Returns:
        Transformed source using mx.* (mlx.core) APIs
    """
    tree = ast.parse(jax_source)
    transformer = JaxToMlxTransformer()
    new_tree = transformer.visit(tree)

    # Remove None statements (from deleted imports)
    new_tree.body = [stmt for stmt in new_tree.body if stmt is not None]

    ast.fix_missing_locations(new_tree)
    return ast.unparse(new_tree)


# ---------------------------------------------------------------------------
# Runtime helpers injected into the exec namespace
# ---------------------------------------------------------------------------

def mlx_select(condlist, choicelist, default):
    """Replacement for jnp.select using nested mx.where."""
    import mlx.core as mx
    result = default
    for cond, choice in reversed(list(zip(condlist, choicelist))):
        result = mx.where(cond, choice, result)
    return result


def mlx_while_loop(cond_fn, body_fn, init_val):
    """Replacement for lax.while_loop using a Python while loop.

    Note: This loses XLA kernel fusion but is functionally correct.
    MLX's lazy evaluation + mx.eval() provides some compensation.
    """
    import mlx.core as mx
    val = init_val
    while cond_fn(val):
        val = body_fn(val)
        mx.eval(val)  # Force evaluation each iteration to avoid graph buildup
    return val


def get_mlx_exec_namespace():
    """Get the namespace dict for exec'ing transformed MLX code.

    Returns a dict with 'mx' and helper functions that the transformed
    code may reference.
    """
    import mlx.core as mx
    return {
        "mx": mx,
        "_mlx_select": mlx_select,
        "_mlx_while_loop": mlx_while_loop,
    }


# ---------------------------------------------------------------------------
# CLI: transform a file or stdin
# ---------------------------------------------------------------------------

if __name__ == "__main__":
    if len(sys.argv) > 1:
        with open(sys.argv[1]) as f:
            source = f.read()
    else:
        source = sys.stdin.read()

    print(jax_to_mlx(source))
